{{- if .Values.html }}
# only created when html value is set — used to serve a custom index.html via nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-html
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride }}
data:
  index.html: |
    {{ .Values.html | nindent 4 }}
{{- end }}
