"args": []
"image":
  "pullPolicy": "IfNotPresent"
  "repository": "nginx"
  "tag": "alpine"
"name": "frontend"
"replicaCount": 1
"resources":
  "limits":
    "cpu": "100m"
    "memory": "128Mi"
  "requests":
    "cpu": "50m"
    "memory": "64Mi"
"service":
  "nodePort": 30081
  "port": 80
