# staging frontend — re-generate with: cd envs/staging/frontend && terragrunt apply

replicaCount: 2

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

nameOverride: frontend
args: []

service:
  type: NodePort
  port: 80
  nodePort: 30083

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

networkPolicy:
  enabled: true
  ingressFromApp: ""
