replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

name: ""

args: []

service:
  type: ClusterIP
  port: 80
  nodePort: null

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

networkPolicy:
  enabled: true
  ingressFromApp: ""
