"args":
- "-text=hello world"
- "-listen=:5678"
"image":
  "pullPolicy": "IfNotPresent"
  "repository": "hashicorp/http-echo"
  "tag": "latest"
"name": "backend"
"replicaCount": 2
"resources":
  "limits":
    "cpu": "200m"
    "memory": "128Mi"
  "requests":
    "cpu": "100m"
    "memory": "64Mi"
"service":
  "nodePort": null
  "port": 5678
